### PR TITLE
Move to stable

### PR DESCRIPTION
**Pull request by ecclarke42**
I'd love to use this library for a work project, but I'm not sure I'm willing to move everything to nightly for it. Here's a quick stab at building it on stable, with some updated/relaxed dependencies!

At the very least, this will build on stable, but tests still require nightly for some of the proc_macro/codegen parts.

The nightly parts still present are gated by a `#[cfg(nightly)]`, but I'm not sure those are all necessary, since they primarily deal with `NoneError`, which is pretty easily replaced by `.ok_or(...)`. I may add another commit adding `thiserror` support to clean up `GraphFailure` a bit.

Would love some feedback or ideas on how to take this the rest of the way!

Ref: #290

### CODE REVIEW

**Comment by sreeise** [comment]
Hey, thanks for working on this. I for sure want to move to stable and its become a higher priority after several people have asked for it. 

To give some context, I am currently working on refactoring the codegen project because of a few issues I have run into, that have made parsing OpenAPI configs and building from that more complicated than I wanted/anticipated. I am still going to be using the OpenAPI config but im taking a cleaner approach to make the project more stable and useful going forward.

Getting the codegen project corrected has been my main priority, but right after that I want the priority to be moving to stable. 
I would still love to see a better implementation for errors, and if your willing to put in a separate PR, I would be happy to approve a merge for that.

For the actual work of moving to stable, I believe it may need to be broken up into a few different parts, one of those being removing `NoneError` from `GraphFailure`. 

```rust
        #[cfg(nightly)]
        let url = upload_session["uploadUrl"].as_str()?;
        #[cfg(not(nightly))]
        let url = upload_session["uploadUrl"]
            .as_str()
            .ok_or(GraphFailure::not_found("NoneError"))?;
```
Honestly, your right about just using ok_or, it just makes more sense and there is no point in trying to support `NoneError` anymore. So, just doing

```rust
        let url = upload_session["uploadUrl"]
            .as_str()
            .ok_or(GraphFailure::not_found("NoneError"))?;
```

is completely fine with me. I have technically already removed it in my codegen branch, but again I am always open to PR's and people contributing to the project.

The second issue is dealing with the nightly features which you have already noticed. I think it would be fun to have nightly gated features but honestly that would add more work in the future because it would have to be maintained (I do this in my free time). Getting the whole project on stable would be preferable and more people would be able to use it. 

I am sure there is more issues we would run into with moving to stable that I am not thinking of right now, but I think this is a starting point and if your willing help figure out what those issues are and possibly help create some issues on GitHub for that work then I am all for getting this rolling.

**Comment by ecclarke42** [comment]
Yeah, of course. If it makes things easier from a branch/repo management perspective, feel free to just use whatever commits I make on this branch as inspiration for stuff to roll into your active branch.

I think from a user perspective, I wouldn't mind too much if the codegen components still require nightly, since the codegen output is committed to the main crate (i.e. you shouldn't need to be on nightly to pull the main crate from crates.io).

What other nightly is there in the non-codegen parts of the repo? I commented out the two `feature` attrs in the main crate's lib and everything seemed to still work fine? Maybe they're not necessary anymore?

I could quickly add something to replace `rocket` in the tests. In future testing, will there ever need to be other listeners besides `/redirect`? Just setting up a `hyper` listener would be pretty simple (and already in the dependency tree), but throwing a [`warp`](https://github.com/seanmonstar/warp) server together is nearly as easy and probably more extensible.

**Comment by sreeise** [comment]
You may be right about the two nightly features in the main crate, Its been a while since I added those. 

I made a ticket for the graph-error changes, https://github.com/sreeise/graph-rs/issues/312

There are a few variations of the listeners but all them use redirect:
- https://github.com/sreeise/graph-rs/blob/23700f19a17dd39bb8282a6acb62c697b72f23fe/examples/rocket_open_id_code.rs#L63
- https://github.com/sreeise/graph-rs/blob/23700f19a17dd39bb8282a6acb62c697b72f23fe/examples/rocket_example.rs#L147
- https://github.com/sreeise/graph-rs/blob/23700f19a17dd39bb8282a6acb62c697b72f23fe/examples/rocket_example_with_state.rs#L79
- https://github.com/sreeise/graph-rs/blob/23700f19a17dd39bb8282a6acb62c697b72f23fe/examples/auth_code_grant_pkce.rs#L82
- https://github.com/sreeise/graph-rs/blob/23700f19a17dd39bb8282a6acb62c697b72f23fe/examples/auth_code_grant.rs#L51

I also made a ticket for the rocket changes: https://github.com/sreeise/graph-rs/issues/313

For PR's that people do I generally just like them to be focused on a single change at a time because they are easier to review/reason about. I will admit that I do not always follow those rules when its my own work (at least on this project) but I really should :)

**Comment by ecclarke42** [comment]
Totally fair! I'll close this and make some of those changes on individual branches of my fork, then open a few PRs. Thanks for your help, and sorry for all the stuff I'll probably be throwing your way!

**Pull request closed without merging**
