### PR TITLE
Replace rocket with warp

### LINKED ISSUE #313: Remove rocket dependency - Move to Stable
Rocket needs to be removed from the examples and replaced with a suitable web framework or manual implementation that can be used on Rust stable.

### PR DESCRIPTION
**Pull request by ecclarke42**
Closes #313 

- Replaces the examples' `rocket` server with a similar `warp` test server. The test server supports graceful shutdown and a `serve_once` function that will automatically shut down the server after one request (as is often the case with the redirection functions)
- Updates project dependencies for `tokio`/`reqwest`/etc to remove some of the duplicates
- Also includes some clippy test/example fixes.

### CODE REVIEW

**Comment by sreeise** [comment]
So I also made changes for removing rocket, not knowing you were working on that too, because right now the tests/builds are failing due to Rocket now requiring a newer rustc version. I also accidentally referenced your PR in my commit :facepalm: instead of #313 so that is why you see GitHub showing I referenced your PR. 

To make this easier, I am going to go ahead an incorporate most of your changes into my branch and go ahead and get it put on master, and then ill take a look at your other two PR's. Let me know whether or not this is ok with you, meaning the commits won't show that you did the work.

**Comment by sreeise** [comment]
Also, you will need to pull in the latest master.

**Comment by ecclarke42** [comment]
Yeah, that's totally fine with me! I think so long as the result is the same. I'm more interested in just using the library on stable, so updating the examples is just a means to an end there.

If it's cleaner, I can always close this PR if you prefer that!

**Comment by sreeise** [comment]
> Yeah, that's totally fine with me! I think so long as the result is the same. I'm more interested in just using the library on stable, so updating the examples is just a means to an end there.
> 
> If it's cleaner, I can always close this PR if you prefer that!

I would definitely rather you get credit for your work, and by merging PR's, but thank you for contributing as well. On this one occasion, it was just easier that I add your changes to my branch. But in the future, im gonna do normal merges.

**Pull request closed without merging**
